/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealersRouteImport } from './routes/dealers'
import { Route as DebtRouteImport } from './routes/debt'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as DealersIdRouteImport } from './routes/dealers_.$id'
import { Route as OrdersIdRouteImport } from './routes/orders_.$id'
import { Route as OrdersNewRouteImport } from './routes/orders_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersRoute = DealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtRoute = DebtRouteImport.update({
  id: '/debt',
  path: '/debt',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersIdRoute = DealersIdRouteImport.update({
  id: '/dealers_/$id',
  path: '/dealers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders_/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dealers': typeof DealersRoute
  '/debt': typeof DebtRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/shipping': typeof ShippingRoute
  '/stats': typeof StatsRoute
  '/visits': typeof VisitsRoute
  '/dealers/$id': typeof DealersIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dealers': typeof DealersRoute
  '/debt': typeof DebtRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/shipping': typeof ShippingRoute
  '/stats': typeof StatsRoute
  '/visits': typeof VisitsRoute
  '/dealers/$id': typeof DealersIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dealers': typeof DealersRoute
  '/debt': typeof DebtRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/shipping': typeof ShippingRoute
  '/stats': typeof StatsRoute
  '/visits': typeof VisitsRoute
  '/dealers_/$id': typeof DealersIdRoute
  '/orders_/$id': typeof OrdersIdRoute
  '/orders_/new': typeof OrdersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dealers'
    | '/debt'
    | '/orders'
    | '/products'
    | '/shipping'
    | '/stats'
    | '/visits'
    | '/dealers/$id'
    | '/orders/$id'
    | '/orders/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dealers'
    | '/debt'
    | '/orders'
    | '/products'
    | '/shipping'
    | '/stats'
    | '/visits'
    | '/dealers/$id'
    | '/orders/$id'
    | '/orders/new'
  id:
    | '__root__'
    | '/'
    | '/dealers'
    | '/debt'
    | '/orders'
    | '/products'
    | '/shipping'
    | '/stats'
    | '/visits'
    | '/dealers_/$id'
    | '/orders_/$id'
    | '/orders_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DealersRoute: typeof DealersRoute
  DebtRoute: typeof DebtRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  ShippingRoute: typeof ShippingRoute
  StatsRoute: typeof StatsRoute
  VisitsRoute: typeof VisitsRoute
  DealersIdRoute: typeof DealersIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers': {
      id: '/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof DealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debt': {
      id: '/debt'
      path: '/debt'
      fullPath: '/debt'
      preLoaderRoute: typeof DebtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers_/$id': {
      id: '/dealers_/$id'
      path: '/dealers/$id'
      fullPath: '/dealers/$id'
      preLoaderRoute: typeof DealersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/$id': {
      id: '/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/new': {
      id: '/orders_/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DealersRoute: DealersRoute,
  DebtRoute: DebtRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  ShippingRoute: ShippingRoute,
  StatsRoute: StatsRoute,
  VisitsRoute: VisitsRoute,
  DealersIdRoute: DealersIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersNewRoute: OrdersNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
